#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

#ifkernel=$(git remote -v|tail -1|grep -o "kernel/common")
#echo "ifkernel:$ifkernel"


PRE_COMMIT_PATCH=".git/hooks/pre-commit"
test -x "$PRE_COMMIT_PATCH"
if [ $? = 0 ];then
    exec "$PRE_COMMIT_PATCH"
else
    echo Please check whether you have got "$GIT_DIR/hooks/pre-commit" and ensure it must be executable
fi
